version: '2'

services:
  direwolf:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: direwolf
    volumes:
      - ./direwolf.conf:/direwolf/direwolf.conf
    devices:
      - /dev/snd:/dev/snd
      - /dev/hidraw1:/dev/hidraw1
      - /dev/hidraw4:/dev/hidraw4
      - /dev/hidraw3:/dev/hidraw3
    restart: unless-stopped
