version: '2'
services:
  direwolf:
    image: stephenhouser/direwolf:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "8888:8000"
    volumes:
      - /share/homes/houser/containers/direwolf/direwolf-N1SH.conf:/etc/direwolf.conf
    devices:
      - /dev/snd:/dev/snd
      - /dev/hidraw0:/dev/cm108

